import { relative, dirname, basename } from 'node:path'
import type { PropInfo } from '../types.js'
import type { analyzeStoryFile } from './scanner.js'

interface StoryFileInfo {
  filePath: string
  analysis: ReturnType<typeof analyzeStoryFile>
  props: PropInfo[]
}

/**
 * Generate the content of studio.gen.ts from analyzed story files.
 */
export function generateStudioGenFile(
  files: StoryFileInfo[],
  genFilePath: string,
): string {
  const lines: string[] = [
    '// studio.gen.ts — auto-generated by @dennation/studio, do not edit',
    "import { resolveStories } from '@dennation/studio/runtime'",
    '',
  ]

  const componentVars: string[] = []

  for (let i = 0; i < files.length; i++) {
    const { filePath, analysis, props } = files[i]
    const prefix = `_c${i}`
    const importPath = buildRelativeImport(genFilePath, filePath)

    // Build import statement
    const imports: string[] = []
    if (analysis.defaultExport) {
      imports.push(prefix)
    }
    for (const name of analysis.namedExports) {
      imports.push(`${name} as ${prefix}_${name}`)
    }

    if (imports.length > 0) {
      lines.push(`import ${formatImports(imports, analysis.defaultExport, prefix)} from '${importPath}'`)
    }

    // Generate props constant
    const propsVar = `${prefix}Props`
    lines.push('')
    lines.push(`const ${propsVar} = ${JSON.stringify(props, null, 2)}`)

    // Build stories array
    const storiesEntries = analysis.namedExports.map(
      (name) => `{ name: '${name}', story: ${prefix}_${name} }`,
    )

    // resolveStories call
    lines.push('')
    lines.push(`const ${prefix}Resolved = resolveStories(${prefix}, {`)
    lines.push(`  props: ${propsVar},`)
    lines.push(`  stories: [${storiesEntries.join(', ')}],`)
    lines.push('})')

    componentVars.push(`${prefix}Resolved`)
  }

  // Default export — array of resolved components
  lines.push('')
  lines.push(`export default [${componentVars.join(', ')}]`)
  lines.push('')

  return lines.join('\n')
}

function formatImports(
  imports: string[],
  hasDefault: boolean,
  defaultName: string,
): string {
  if (hasDefault) {
    const named = imports.filter((i) => i !== defaultName)
    if (named.length > 0) {
      return `${defaultName}, { ${named.join(', ')} }`
    }
    return defaultName
  }
  return `{ ${imports.join(', ')} }`
}

function buildRelativeImport(from: string, to: string): string {
  const fromDir = dirname(from)
  let rel = relative(fromDir, to)
  // Remove .tsx extension for import
  rel = rel.replace(/\.tsx?$/, '')
  // Ensure relative path
  if (!rel.startsWith('.')) {
    rel = './' + rel
  }
  return rel
}
