/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as GettingStartedRouteImport } from "./pages/getting-started";
import { Route as IndexRouteImport } from "./pages/index";

const GettingStartedRoute = GettingStartedRouteImport.update({
	id: "/getting-started",
	path: "/getting-started",
	getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/getting-started": typeof GettingStartedRoute;
}
export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/getting-started": typeof GettingStartedRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/": typeof IndexRoute;
	"/getting-started": typeof GettingStartedRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/getting-started";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/getting-started";
	id: "__root__" | "/" | "/getting-started";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	GettingStartedRoute: typeof GettingStartedRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/getting-started": {
			id: "/getting-started";
			path: "/getting-started";
			fullPath: "/getting-started";
			preLoaderRoute: typeof GettingStartedRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	GettingStartedRoute: GettingStartedRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();
