/*
 * A function's TypeScript signature, rendered as a code block whose parameter
 * names and return type are clickable. Each link jumps to the section that
 * documents it — parameter tokens to `#parameters`, the return token to
 * `#returns` — so the signature doubles as in-page navigation.
 *
 * The signature is authored as a token stream rather than a plain string so the
 * links can be placed exactly. Build it with the `txt` / `ref` helpers:
 *
 *   <FunctionSignature
 *     tokens={[
 *       txt("function slugify("),
 *       ref("s", "#parameters"), txt(": string): "),
 *       ref("string", "#returns"),
 *     ]}
 *   />
 *
 * When the autogenerated signatures land, the same component renders the
 * injected token model — only the source of `tokens` changes, not the markup.
 */

/** One piece of a rendered signature: inert text, or a token linking to a section. */
export type SigToken =
	| { kind: "text"; value: string }
	| { kind: "link"; value: string; to: string };

/** Inert signature text (keywords, generics, punctuation). */
export const txt = (value: string): SigToken => ({ kind: "text", value });

/** A clickable signature token — a parameter name or the return type. */
export const ref = (value: string, to: string): SigToken => ({
	kind: "link",
	value,
	to,
});

export interface FunctionSignatureProps {
	tokens: SigToken[];
}

const linkClass =
	"text-accent underline decoration-accent-soft-border decoration-1 underline-offset-2 rounded-[3px] hover:decoration-accent focus-visible:outline-2 focus-visible:outline-accent focus-visible:outline-offset-1";

/** Render a function signature with clickable parameter and return tokens. */
export function FunctionSignature({ tokens }: FunctionSignatureProps) {
	return (
		<div className="border border-border rounded-(--radius-token) overflow-hidden bg-code-bg">
			<div className="overflow-x-auto">
				<pre className="m-0 px-4.5 py-4 font-mono text-[13px] leading-[1.65] text-fg">
					<code className="font-mono">
						{tokens.map((tok, i) =>
							tok.kind === "text" ? (
								// biome-ignore lint/suspicious/noArrayIndexKey: tokens are positional
								<span key={i}>{tok.value}</span>
							) : (
								<a
									// biome-ignore lint/suspicious/noArrayIndexKey: tokens are positional
									key={i}
									href={tok.to}
									className={linkClass}
								>
									{tok.value}
								</a>
							),
						)}
					</code>
				</pre>
			</div>
		</div>
	);
}
