// studio.gen.ts — auto-generated by @dennation/studio, do not edit
import { resolveStories } from '@dennation/studio/runtime'
import type { PropInfo } from '@dennation/studio'

import _c0, { Sizes as _c0_Sizes, Variants as _c0_Variants } from './src/components/ComposedButton.stories'

const _c0Props: PropInfo[] = [
  {
    "name": "disabled",
    "optional": true,
    "type": {
      "kind": "unknown",
      "raw": "... | ..."
    }
  },
  {
    "name": "children",
    "optional": false,
    "type": {
      "kind": "node"
    }
  },
  {
    "name": "onClick",
    "optional": true,
    "type": {
      "kind": "unknown",
      "raw": "... | ..."
    }
  },
  {
    "name": "onFocus",
    "optional": true,
    "type": {
      "kind": "unknown",
      "raw": "... | ..."
    }
  },
  {
    "name": "size",
    "optional": false,
    "type": {
      "kind": "literal",
      "values": [
        "lg",
        "md",
        "sm"
      ]
    }
  },
  {
    "name": "variant",
    "optional": false,
    "type": {
      "kind": "literal",
      "values": [
        "ghost",
        "primary",
        "secondary"
      ]
    }
  }
]

const _c0Resolved = resolveStories(_c0, {
  props: _c0Props,
  stories: [{ name: 'Sizes', story: _c0_Sizes }, { name: 'Variants', story: _c0_Variants }],
})
import _c1, { Sizes as _c1_Sizes, Variants as _c1_Variants, WithIcon as _c1_WithIcon } from './src/components/Button.stories'

const _c1Props: PropInfo[] = [
  {
    "name": "size",
    "optional": false,
    "type": {
      "kind": "literal",
      "values": [
        "lg",
        "md",
        "sm"
      ]
    }
  },
  {
    "name": "variant",
    "optional": false,
    "type": {
      "kind": "literal",
      "values": [
        "ghost",
        "primary",
        "secondary"
      ]
    }
  },
  {
    "name": "disabled",
    "optional": true,
    "type": {
      "kind": "unknown",
      "raw": "... | ..."
    }
  },
  {
    "name": "children",
    "optional": false,
    "type": {
      "kind": "node"
    }
  },
  {
    "name": "onClick",
    "optional": true,
    "type": {
      "kind": "unknown",
      "raw": "... | ..."
    }
  }
]

const _c1Resolved = resolveStories(_c1, {
  props: _c1Props,
  stories: [{ name: 'Sizes', story: _c1_Sizes }, { name: 'Variants', story: _c1_Variants }, { name: 'WithIcon', story: _c1_WithIcon }],
})

export default [_c0Resolved, _c1Resolved]
