// ui-studio-registry.gen.ts — auto-generated by @dennation/ui-studio, do not edit
import type { RegistryEntry } from '@dennation/ui-studio'
import meta from './ui-studio-meta.gen'
import _Switch, { Default as _Switch_Default, Sizes as _Switch_Sizes, Colors as _Switch_Colors, States as _Switch_States, Matrix as _Switch_Matrix } from './src/stories/Switch.stories'
import _Input, { Default as _Input_Default, Sizes as _Input_Sizes, Variants as _Input_Variants, Colors as _Input_Colors, States as _Input_States, Matrix as _Input_Matrix } from './src/stories/Input.stories'
import _Checkbox, { Default as _Checkbox_Default, Sizes as _Checkbox_Sizes, Colors as _Checkbox_Colors, States as _Checkbox_States, Matrix as _Checkbox_Matrix } from './src/stories/Checkbox.stories'
import _Button, { Default as _Button_Default, Sizes as _Button_Sizes, Variants as _Button_Variants, Colors as _Button_Colors, Radiuses as _Button_Radiuses, Disabled as _Button_Disabled, Loading as _Button_Loading, Matrix as _Button_Matrix } from './src/stories/Button.stories'

const registry: RegistryEntry[] = [
  {
    config: _Switch,
    stories: { Default: _Switch_Default, Sizes: _Switch_Sizes, Colors: _Switch_Colors, States: _Switch_States, Matrix: _Switch_Matrix },
    meta: meta['src/stories/Switch.stories.tsx'],
  },
  {
    config: _Input,
    stories: { Default: _Input_Default, Sizes: _Input_Sizes, Variants: _Input_Variants, Colors: _Input_Colors, States: _Input_States, Matrix: _Input_Matrix },
    meta: meta['src/stories/Input.stories.tsx'],
  },
  {
    config: _Checkbox,
    stories: { Default: _Checkbox_Default, Sizes: _Checkbox_Sizes, Colors: _Checkbox_Colors, States: _Checkbox_States, Matrix: _Checkbox_Matrix },
    meta: meta['src/stories/Checkbox.stories.tsx'],
  },
  {
    config: _Button,
    stories: { Default: _Button_Default, Sizes: _Button_Sizes, Variants: _Button_Variants, Colors: _Button_Colors, Radiuses: _Button_Radiuses, Disabled: _Button_Disabled, Loading: _Button_Loading, Matrix: _Button_Matrix },
    meta: meta['src/stories/Button.stories.tsx'],
  },
]

export default registry
