// ui-studio.gen.ts — auto-generated by @dennation/ui-studio, do not edit
import { resolve } from '@dennation/ui-studio'
import type { PropInfo } from '@dennation/ui-studio'

import _Button, { Sizes as _Button_Sizes } from './src/stories/Butto.stories'

const _ButtonProps: PropInfo[] = []

const _ButtonResolved = resolve(_Button, {
  props: _ButtonProps,
  stories: [{ name: 'Sizes', story: _Button_Sizes }],
})

export default [_ButtonResolved]
