// studio.meta.gen.ts — auto-generated by @dennation/ui-studio, do not edit
import type { ComponentMeta } from '@dennation/ui-studio'

const meta: Record<string, ComponentMeta> = {
  "src/stories/Switch.stories.tsx": {
    "props": [
      {
        "name": "color",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "default",
            "primary",
            "secondary",
            "success",
            "warning",
            "danger"
          ]
        }
      },
      {
        "name": "size",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "sm",
            "md",
            "lg"
          ]
        }
      },
      {
        "name": "disabled",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      },
      {
        "name": "isSelected",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      }
    ]
  },
  "src/stories/Input.stories.tsx": {
    "props": [
      {
        "name": "color",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "default",
            "primary",
            "secondary",
            "success",
            "warning",
            "danger"
          ]
        }
      },
      {
        "name": "size",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "sm",
            "md",
            "lg"
          ]
        }
      },
      {
        "name": "disabled",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      },
      {
        "name": "isReadOnly",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      },
      {
        "name": "isRequired",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      },
      {
        "name": "variant",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "flat",
            "faded",
            "bordered",
            "underlined"
          ]
        }
      },
      {
        "name": "radius",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "sm",
            "md",
            "lg",
            "none",
            "full"
          ]
        }
      }
    ]
  },
  "src/stories/Checkbox.stories.tsx": {
    "props": [
      {
        "name": "color",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "default",
            "primary",
            "secondary",
            "success",
            "warning",
            "danger"
          ]
        }
      },
      {
        "name": "size",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "sm",
            "md",
            "lg"
          ]
        }
      },
      {
        "name": "disabled",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      },
      {
        "name": "isSelected",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      },
      {
        "name": "radius",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "sm",
            "md",
            "lg",
            "none",
            "full"
          ]
        }
      }
    ]
  },
  "src/stories/Button.stories.tsx": {
    "props": [
      {
        "name": "color",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "default",
            "primary",
            "secondary",
            "success",
            "warning",
            "danger"
          ]
        }
      },
      {
        "name": "size",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "sm",
            "md",
            "lg"
          ]
        }
      },
      {
        "name": "disabled",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      },
      {
        "name": "variant",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "flat",
            "faded",
            "bordered",
            "solid",
            "light",
            "shadow",
            "ghost"
          ]
        }
      },
      {
        "name": "radius",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "sm",
            "md",
            "lg",
            "none",
            "full"
          ]
        }
      },
      {
        "name": "isLoading",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      }
    ]
  }
}

export default meta
