// snippets.gen.ts — auto-generated by @dennation/typebook, do not edit
import type { SnippetMap } from '@dennation/typebook'

export const snippets = {
  "button-group": "<div className=\"st:flex st:gap-2\">\n  <Button size=\"sm\">Small</Button>\n  <Button size=\"md\">Medium</Button>\n  <Button size=\"lg\">Large</Button>\n</div>",
} as const satisfies SnippetMap
