// ui-registry.gen.ts — auto-generated by @dennation/typebook, do not edit
import type { UIRegistry } from "@dennation/typebook";
import { Button } from "./components/Button";

export const uiRegistry = {
	button: {
		componentName: "Button",
		component: Button,
		props: [
			{
				name: "children",
				optional: false,
				type: {
					kind: "node",
				},
				description: "Content rendered inside the button.",
			},
			{
				name: "size",
				optional: true,
				type: {
					kind: "literal",
					values: ["sm", "md", "lg"],
				},
				description: "Visual size of the button.",
				defaultValue: "'md'",
			},
			{
				name: "variant",
				optional: true,
				type: {
					kind: "literal",
					values: ["solid", "outline", "ghost"],
				},
				description: "Style variant — controls fill and border.",
				defaultValue: "'solid'",
			},
			{
				name: "color",
				optional: true,
				type: {
					kind: "literal",
					values: ["primary", "secondary", "danger"],
				},
				description: "Semantic color token.",
				defaultValue: "'primary'",
			},
			{
				name: "disabled",
				optional: true,
				type: {
					kind: "boolean",
				},
				description:
					"When true, the button is non-interactive and visually dimmed.",
			},
			{
				name: "onClick",
				optional: true,
				type: {
					kind: "function",
				},
				description: "Fired on click. Ignored when `disabled` is true.",
			},
		],
	},
} as const satisfies UIRegistry;
