/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as DocsRouteRouteImport } from './pages/docs/route'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DocsIndexRouteImport } from './pages/docs/index'
import { Route as DocsGuidesVariantsRouteImport } from './pages/docs/guides/variants'
import { Route as DocsGuidesThemingRouteImport } from './pages/docs/guides/theming'
import { Route as DocsGuidesStoryRouteImport } from './pages/docs/guides/story'
import { Route as DocsGuidesSnippetRouteImport } from './pages/docs/guides/snippet'
import { Route as DocsGuidesPlaygroundRouteImport } from './pages/docs/guides/playground'
import { Route as DocsGuidesMatrixRouteImport } from './pages/docs/guides/matrix'
import { Route as DocsGettingStartedQuickStartRouteImport } from './pages/docs/getting-started/quick-start'
import { Route as DocsGettingStartedIntroductionRouteImport } from './pages/docs/getting-started/introduction'
import { Route as DocsGettingStartedInstallationRouteImport } from './pages/docs/getting-started/installation'
import { Route as DocsComponentsThemeToggleRouteImport } from './pages/docs/components/theme-toggle'
import { Route as DocsComponentsTabsRouteImport } from './pages/docs/components/tabs'
import { Route as DocsComponentsTablesRouteImport } from './pages/docs/components/tables'
import { Route as DocsComponentsStepsRouteImport } from './pages/docs/components/steps'
import { Route as DocsComponentsProseRouteImport } from './pages/docs/components/prose'
import { Route as DocsComponentsNavigationRouteImport } from './pages/docs/components/navigation'
import { Route as DocsComponentsLayoutRouteImport } from './pages/docs/components/layout'
import { Route as DocsComponentsIconRouteImport } from './pages/docs/components/icon'
import { Route as DocsComponentsErrorBoundaryRouteImport } from './pages/docs/components/error-boundary'
import { Route as DocsComponentsCopyCommandRouteImport } from './pages/docs/components/copy-command'
import { Route as DocsComponentsCodeBlockRouteImport } from './pages/docs/components/code-block'
import { Route as DocsComponentsCardsRouteImport } from './pages/docs/components/cards'
import { Route as DocsComponentsCalloutRouteImport } from './pages/docs/components/callout'
import { Route as DocsComponentsButtonRouteImport } from './pages/docs/components/button'
import { Route as DocsComponentsAccordionRouteImport } from './pages/docs/components/accordion'

const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesVariantsRoute = DocsGuidesVariantsRouteImport.update({
  id: '/guides/variants',
  path: '/guides/variants',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesThemingRoute = DocsGuidesThemingRouteImport.update({
  id: '/guides/theming',
  path: '/guides/theming',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesStoryRoute = DocsGuidesStoryRouteImport.update({
  id: '/guides/story',
  path: '/guides/story',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesSnippetRoute = DocsGuidesSnippetRouteImport.update({
  id: '/guides/snippet',
  path: '/guides/snippet',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesPlaygroundRoute = DocsGuidesPlaygroundRouteImport.update({
  id: '/guides/playground',
  path: '/guides/playground',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGuidesMatrixRoute = DocsGuidesMatrixRouteImport.update({
  id: '/guides/matrix',
  path: '/guides/matrix',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsGettingStartedQuickStartRoute =
  DocsGettingStartedQuickStartRouteImport.update({
    id: '/getting-started/quick-start',
    path: '/getting-started/quick-start',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGettingStartedIntroductionRoute =
  DocsGettingStartedIntroductionRouteImport.update({
    id: '/getting-started/introduction',
    path: '/getting-started/introduction',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsGettingStartedInstallationRoute =
  DocsGettingStartedInstallationRouteImport.update({
    id: '/getting-started/installation',
    path: '/getting-started/installation',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsComponentsThemeToggleRoute =
  DocsComponentsThemeToggleRouteImport.update({
    id: '/components/theme-toggle',
    path: '/components/theme-toggle',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsComponentsTabsRoute = DocsComponentsTabsRouteImport.update({
  id: '/components/tabs',
  path: '/components/tabs',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsTablesRoute = DocsComponentsTablesRouteImport.update({
  id: '/components/tables',
  path: '/components/tables',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsStepsRoute = DocsComponentsStepsRouteImport.update({
  id: '/components/steps',
  path: '/components/steps',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsProseRoute = DocsComponentsProseRouteImport.update({
  id: '/components/prose',
  path: '/components/prose',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsNavigationRoute =
  DocsComponentsNavigationRouteImport.update({
    id: '/components/navigation',
    path: '/components/navigation',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsComponentsLayoutRoute = DocsComponentsLayoutRouteImport.update({
  id: '/components/layout',
  path: '/components/layout',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsIconRoute = DocsComponentsIconRouteImport.update({
  id: '/components/icon',
  path: '/components/icon',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsErrorBoundaryRoute =
  DocsComponentsErrorBoundaryRouteImport.update({
    id: '/components/error-boundary',
    path: '/components/error-boundary',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsComponentsCopyCommandRoute =
  DocsComponentsCopyCommandRouteImport.update({
    id: '/components/copy-command',
    path: '/components/copy-command',
    getParentRoute: () => DocsRouteRoute,
  } as any)
const DocsComponentsCodeBlockRoute = DocsComponentsCodeBlockRouteImport.update({
  id: '/components/code-block',
  path: '/components/code-block',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsCardsRoute = DocsComponentsCardsRouteImport.update({
  id: '/components/cards',
  path: '/components/cards',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsCalloutRoute = DocsComponentsCalloutRouteImport.update({
  id: '/components/callout',
  path: '/components/callout',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsButtonRoute = DocsComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => DocsRouteRoute,
} as any)
const DocsComponentsAccordionRoute = DocsComponentsAccordionRouteImport.update({
  id: '/components/accordion',
  path: '/components/accordion',
  getParentRoute: () => DocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/callout': typeof DocsComponentsCalloutRoute
  '/docs/components/cards': typeof DocsComponentsCardsRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/copy-command': typeof DocsComponentsCopyCommandRoute
  '/docs/components/error-boundary': typeof DocsComponentsErrorBoundaryRoute
  '/docs/components/icon': typeof DocsComponentsIconRoute
  '/docs/components/layout': typeof DocsComponentsLayoutRoute
  '/docs/components/navigation': typeof DocsComponentsNavigationRoute
  '/docs/components/prose': typeof DocsComponentsProseRoute
  '/docs/components/steps': typeof DocsComponentsStepsRoute
  '/docs/components/tables': typeof DocsComponentsTablesRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/theme-toggle': typeof DocsComponentsThemeToggleRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/getting-started/introduction': typeof DocsGettingStartedIntroductionRoute
  '/docs/getting-started/quick-start': typeof DocsGettingStartedQuickStartRoute
  '/docs/guides/matrix': typeof DocsGuidesMatrixRoute
  '/docs/guides/playground': typeof DocsGuidesPlaygroundRoute
  '/docs/guides/snippet': typeof DocsGuidesSnippetRoute
  '/docs/guides/story': typeof DocsGuidesStoryRoute
  '/docs/guides/theming': typeof DocsGuidesThemingRoute
  '/docs/guides/variants': typeof DocsGuidesVariantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/callout': typeof DocsComponentsCalloutRoute
  '/docs/components/cards': typeof DocsComponentsCardsRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/copy-command': typeof DocsComponentsCopyCommandRoute
  '/docs/components/error-boundary': typeof DocsComponentsErrorBoundaryRoute
  '/docs/components/icon': typeof DocsComponentsIconRoute
  '/docs/components/layout': typeof DocsComponentsLayoutRoute
  '/docs/components/navigation': typeof DocsComponentsNavigationRoute
  '/docs/components/prose': typeof DocsComponentsProseRoute
  '/docs/components/steps': typeof DocsComponentsStepsRoute
  '/docs/components/tables': typeof DocsComponentsTablesRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/theme-toggle': typeof DocsComponentsThemeToggleRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/getting-started/introduction': typeof DocsGettingStartedIntroductionRoute
  '/docs/getting-started/quick-start': typeof DocsGettingStartedQuickStartRoute
  '/docs/guides/matrix': typeof DocsGuidesMatrixRoute
  '/docs/guides/playground': typeof DocsGuidesPlaygroundRoute
  '/docs/guides/snippet': typeof DocsGuidesSnippetRoute
  '/docs/guides/story': typeof DocsGuidesStoryRoute
  '/docs/guides/theming': typeof DocsGuidesThemingRoute
  '/docs/guides/variants': typeof DocsGuidesVariantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/docs/components/accordion': typeof DocsComponentsAccordionRoute
  '/docs/components/button': typeof DocsComponentsButtonRoute
  '/docs/components/callout': typeof DocsComponentsCalloutRoute
  '/docs/components/cards': typeof DocsComponentsCardsRoute
  '/docs/components/code-block': typeof DocsComponentsCodeBlockRoute
  '/docs/components/copy-command': typeof DocsComponentsCopyCommandRoute
  '/docs/components/error-boundary': typeof DocsComponentsErrorBoundaryRoute
  '/docs/components/icon': typeof DocsComponentsIconRoute
  '/docs/components/layout': typeof DocsComponentsLayoutRoute
  '/docs/components/navigation': typeof DocsComponentsNavigationRoute
  '/docs/components/prose': typeof DocsComponentsProseRoute
  '/docs/components/steps': typeof DocsComponentsStepsRoute
  '/docs/components/tables': typeof DocsComponentsTablesRoute
  '/docs/components/tabs': typeof DocsComponentsTabsRoute
  '/docs/components/theme-toggle': typeof DocsComponentsThemeToggleRoute
  '/docs/getting-started/installation': typeof DocsGettingStartedInstallationRoute
  '/docs/getting-started/introduction': typeof DocsGettingStartedIntroductionRoute
  '/docs/getting-started/quick-start': typeof DocsGettingStartedQuickStartRoute
  '/docs/guides/matrix': typeof DocsGuidesMatrixRoute
  '/docs/guides/playground': typeof DocsGuidesPlaygroundRoute
  '/docs/guides/snippet': typeof DocsGuidesSnippetRoute
  '/docs/guides/story': typeof DocsGuidesStoryRoute
  '/docs/guides/theming': typeof DocsGuidesThemingRoute
  '/docs/guides/variants': typeof DocsGuidesVariantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/'
    | '/docs/components/accordion'
    | '/docs/components/button'
    | '/docs/components/callout'
    | '/docs/components/cards'
    | '/docs/components/code-block'
    | '/docs/components/copy-command'
    | '/docs/components/error-boundary'
    | '/docs/components/icon'
    | '/docs/components/layout'
    | '/docs/components/navigation'
    | '/docs/components/prose'
    | '/docs/components/steps'
    | '/docs/components/tables'
    | '/docs/components/tabs'
    | '/docs/components/theme-toggle'
    | '/docs/getting-started/installation'
    | '/docs/getting-started/introduction'
    | '/docs/getting-started/quick-start'
    | '/docs/guides/matrix'
    | '/docs/guides/playground'
    | '/docs/guides/snippet'
    | '/docs/guides/story'
    | '/docs/guides/theming'
    | '/docs/guides/variants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/docs/components/accordion'
    | '/docs/components/button'
    | '/docs/components/callout'
    | '/docs/components/cards'
    | '/docs/components/code-block'
    | '/docs/components/copy-command'
    | '/docs/components/error-boundary'
    | '/docs/components/icon'
    | '/docs/components/layout'
    | '/docs/components/navigation'
    | '/docs/components/prose'
    | '/docs/components/steps'
    | '/docs/components/tables'
    | '/docs/components/tabs'
    | '/docs/components/theme-toggle'
    | '/docs/getting-started/installation'
    | '/docs/getting-started/introduction'
    | '/docs/getting-started/quick-start'
    | '/docs/guides/matrix'
    | '/docs/guides/playground'
    | '/docs/guides/snippet'
    | '/docs/guides/story'
    | '/docs/guides/theming'
    | '/docs/guides/variants'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/'
    | '/docs/components/accordion'
    | '/docs/components/button'
    | '/docs/components/callout'
    | '/docs/components/cards'
    | '/docs/components/code-block'
    | '/docs/components/copy-command'
    | '/docs/components/error-boundary'
    | '/docs/components/icon'
    | '/docs/components/layout'
    | '/docs/components/navigation'
    | '/docs/components/prose'
    | '/docs/components/steps'
    | '/docs/components/tables'
    | '/docs/components/tabs'
    | '/docs/components/theme-toggle'
    | '/docs/getting-started/installation'
    | '/docs/getting-started/introduction'
    | '/docs/getting-started/quick-start'
    | '/docs/guides/matrix'
    | '/docs/guides/playground'
    | '/docs/guides/snippet'
    | '/docs/guides/story'
    | '/docs/guides/theming'
    | '/docs/guides/variants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/variants': {
      id: '/docs/guides/variants'
      path: '/guides/variants'
      fullPath: '/docs/guides/variants'
      preLoaderRoute: typeof DocsGuidesVariantsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/theming': {
      id: '/docs/guides/theming'
      path: '/guides/theming'
      fullPath: '/docs/guides/theming'
      preLoaderRoute: typeof DocsGuidesThemingRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/story': {
      id: '/docs/guides/story'
      path: '/guides/story'
      fullPath: '/docs/guides/story'
      preLoaderRoute: typeof DocsGuidesStoryRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/snippet': {
      id: '/docs/guides/snippet'
      path: '/guides/snippet'
      fullPath: '/docs/guides/snippet'
      preLoaderRoute: typeof DocsGuidesSnippetRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/playground': {
      id: '/docs/guides/playground'
      path: '/guides/playground'
      fullPath: '/docs/guides/playground'
      preLoaderRoute: typeof DocsGuidesPlaygroundRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/guides/matrix': {
      id: '/docs/guides/matrix'
      path: '/guides/matrix'
      fullPath: '/docs/guides/matrix'
      preLoaderRoute: typeof DocsGuidesMatrixRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/getting-started/quick-start': {
      id: '/docs/getting-started/quick-start'
      path: '/getting-started/quick-start'
      fullPath: '/docs/getting-started/quick-start'
      preLoaderRoute: typeof DocsGettingStartedQuickStartRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/getting-started/introduction': {
      id: '/docs/getting-started/introduction'
      path: '/getting-started/introduction'
      fullPath: '/docs/getting-started/introduction'
      preLoaderRoute: typeof DocsGettingStartedIntroductionRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/getting-started/installation': {
      id: '/docs/getting-started/installation'
      path: '/getting-started/installation'
      fullPath: '/docs/getting-started/installation'
      preLoaderRoute: typeof DocsGettingStartedInstallationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/theme-toggle': {
      id: '/docs/components/theme-toggle'
      path: '/components/theme-toggle'
      fullPath: '/docs/components/theme-toggle'
      preLoaderRoute: typeof DocsComponentsThemeToggleRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/tabs': {
      id: '/docs/components/tabs'
      path: '/components/tabs'
      fullPath: '/docs/components/tabs'
      preLoaderRoute: typeof DocsComponentsTabsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/tables': {
      id: '/docs/components/tables'
      path: '/components/tables'
      fullPath: '/docs/components/tables'
      preLoaderRoute: typeof DocsComponentsTablesRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/steps': {
      id: '/docs/components/steps'
      path: '/components/steps'
      fullPath: '/docs/components/steps'
      preLoaderRoute: typeof DocsComponentsStepsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/prose': {
      id: '/docs/components/prose'
      path: '/components/prose'
      fullPath: '/docs/components/prose'
      preLoaderRoute: typeof DocsComponentsProseRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/navigation': {
      id: '/docs/components/navigation'
      path: '/components/navigation'
      fullPath: '/docs/components/navigation'
      preLoaderRoute: typeof DocsComponentsNavigationRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/layout': {
      id: '/docs/components/layout'
      path: '/components/layout'
      fullPath: '/docs/components/layout'
      preLoaderRoute: typeof DocsComponentsLayoutRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/icon': {
      id: '/docs/components/icon'
      path: '/components/icon'
      fullPath: '/docs/components/icon'
      preLoaderRoute: typeof DocsComponentsIconRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/error-boundary': {
      id: '/docs/components/error-boundary'
      path: '/components/error-boundary'
      fullPath: '/docs/components/error-boundary'
      preLoaderRoute: typeof DocsComponentsErrorBoundaryRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/copy-command': {
      id: '/docs/components/copy-command'
      path: '/components/copy-command'
      fullPath: '/docs/components/copy-command'
      preLoaderRoute: typeof DocsComponentsCopyCommandRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/code-block': {
      id: '/docs/components/code-block'
      path: '/components/code-block'
      fullPath: '/docs/components/code-block'
      preLoaderRoute: typeof DocsComponentsCodeBlockRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/cards': {
      id: '/docs/components/cards'
      path: '/components/cards'
      fullPath: '/docs/components/cards'
      preLoaderRoute: typeof DocsComponentsCardsRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/callout': {
      id: '/docs/components/callout'
      path: '/components/callout'
      fullPath: '/docs/components/callout'
      preLoaderRoute: typeof DocsComponentsCalloutRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/button': {
      id: '/docs/components/button'
      path: '/components/button'
      fullPath: '/docs/components/button'
      preLoaderRoute: typeof DocsComponentsButtonRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/docs/components/accordion': {
      id: '/docs/components/accordion'
      path: '/components/accordion'
      fullPath: '/docs/components/accordion'
      preLoaderRoute: typeof DocsComponentsAccordionRouteImport
      parentRoute: typeof DocsRouteRoute
    }
  }
}

interface DocsRouteRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentsAccordionRoute: typeof DocsComponentsAccordionRoute
  DocsComponentsButtonRoute: typeof DocsComponentsButtonRoute
  DocsComponentsCalloutRoute: typeof DocsComponentsCalloutRoute
  DocsComponentsCardsRoute: typeof DocsComponentsCardsRoute
  DocsComponentsCodeBlockRoute: typeof DocsComponentsCodeBlockRoute
  DocsComponentsCopyCommandRoute: typeof DocsComponentsCopyCommandRoute
  DocsComponentsErrorBoundaryRoute: typeof DocsComponentsErrorBoundaryRoute
  DocsComponentsIconRoute: typeof DocsComponentsIconRoute
  DocsComponentsLayoutRoute: typeof DocsComponentsLayoutRoute
  DocsComponentsNavigationRoute: typeof DocsComponentsNavigationRoute
  DocsComponentsProseRoute: typeof DocsComponentsProseRoute
  DocsComponentsStepsRoute: typeof DocsComponentsStepsRoute
  DocsComponentsTablesRoute: typeof DocsComponentsTablesRoute
  DocsComponentsTabsRoute: typeof DocsComponentsTabsRoute
  DocsComponentsThemeToggleRoute: typeof DocsComponentsThemeToggleRoute
  DocsGettingStartedInstallationRoute: typeof DocsGettingStartedInstallationRoute
  DocsGettingStartedIntroductionRoute: typeof DocsGettingStartedIntroductionRoute
  DocsGettingStartedQuickStartRoute: typeof DocsGettingStartedQuickStartRoute
  DocsGuidesMatrixRoute: typeof DocsGuidesMatrixRoute
  DocsGuidesPlaygroundRoute: typeof DocsGuidesPlaygroundRoute
  DocsGuidesSnippetRoute: typeof DocsGuidesSnippetRoute
  DocsGuidesStoryRoute: typeof DocsGuidesStoryRoute
  DocsGuidesThemingRoute: typeof DocsGuidesThemingRoute
  DocsGuidesVariantsRoute: typeof DocsGuidesVariantsRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentsAccordionRoute: DocsComponentsAccordionRoute,
  DocsComponentsButtonRoute: DocsComponentsButtonRoute,
  DocsComponentsCalloutRoute: DocsComponentsCalloutRoute,
  DocsComponentsCardsRoute: DocsComponentsCardsRoute,
  DocsComponentsCodeBlockRoute: DocsComponentsCodeBlockRoute,
  DocsComponentsCopyCommandRoute: DocsComponentsCopyCommandRoute,
  DocsComponentsErrorBoundaryRoute: DocsComponentsErrorBoundaryRoute,
  DocsComponentsIconRoute: DocsComponentsIconRoute,
  DocsComponentsLayoutRoute: DocsComponentsLayoutRoute,
  DocsComponentsNavigationRoute: DocsComponentsNavigationRoute,
  DocsComponentsProseRoute: DocsComponentsProseRoute,
  DocsComponentsStepsRoute: DocsComponentsStepsRoute,
  DocsComponentsTablesRoute: DocsComponentsTablesRoute,
  DocsComponentsTabsRoute: DocsComponentsTabsRoute,
  DocsComponentsThemeToggleRoute: DocsComponentsThemeToggleRoute,
  DocsGettingStartedInstallationRoute: DocsGettingStartedInstallationRoute,
  DocsGettingStartedIntroductionRoute: DocsGettingStartedIntroductionRoute,
  DocsGettingStartedQuickStartRoute: DocsGettingStartedQuickStartRoute,
  DocsGuidesMatrixRoute: DocsGuidesMatrixRoute,
  DocsGuidesPlaygroundRoute: DocsGuidesPlaygroundRoute,
  DocsGuidesSnippetRoute: DocsGuidesSnippetRoute,
  DocsGuidesStoryRoute: DocsGuidesStoryRoute,
  DocsGuidesThemingRoute: DocsGuidesThemingRoute,
  DocsGuidesVariantsRoute: DocsGuidesVariantsRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRouteRoute: DocsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
