// snippets.gen.ts — auto-generated by @dennation/typebook, do not edit
import type { SnippetMap } from "@dennation/typebook";

export const snippets = {
	"accordion-example":
		'<Accordion\n  items={[\n    {\n      q: "Is only one item open at a time?",\n      a: "Yes — opening an item closes the previous one; clicking the open item closes it.",\n    },\n    {\n      q: "Can answers hold rich content?",\n      a: (\n        <>\n          Yes, <C>a</C> is a <C>ReactNode</C> — code, links and lists\n          all work.\n        </>\n      ),\n    },\n  ]}\n/>',
	"callout-usage":
		'<Callout type="warning" title="Heads up">\n  This runs on the client only.\n</Callout>',
	"cards-example":
		'<Cards>\n  <DocCard\n    icon={<Icon.zap size={20} />}\n    title="Quick Start"\n    desc="From zero to a documented component."\n    onClick={() => go("quick-start")}\n  />\n  <DocCard\n    icon={<Icon.search size={20} />}\n    title="Search"\n    desc="Jump to the SearchPalette docs."\n    onClick={() => go("search")}\n  />\n</Cards>',
	"copy-command-example": '<CopyCommand cmd="pnpm add @dennation/typebook" />',
	"mdtable-example":
		'<MDTable\n  head={["Bundler", "Entry", "Status"]}\n  rows={[\n    ["Vite", <C key="e">@dennation/typebook/vite</C>, "Stable"],\n    ["webpack", <C key="e">@dennation/typebook/webpack</C>, "Stable"],\n    ["esbuild", <C key="e">@dennation/typebook/esbuild</C>, "Stable"],\n  ]}\n/>',
	"props-table-example":
		'<PropsTable\n  props={[\n    {\n      name: "type",\n      type: \'"info" | "warning"\',\n      default: \'"info"\',\n      desc: "Visual intent.",\n    },\n    {\n      name: "children",\n      type: "ReactNode",\n      required: true,\n      desc: "Body.",\n    },\n  ]}\n/>',
	"steps-example":
		'<Steps>\n  <Step title="Install the package">\n    <P>\n      Any content works inside a step — paragraphs, code blocks,\n      callouts.\n    </P>\n  </Step>\n  <Step title="Wire the plugin">\n    <CodeBlock lang="bash" code={`pnpm add @dennation/typebook`} />\n  </Step>\n  <Step title="Render a story">\n    <P>The connector line stops automatically at the last step.</P>\n  </Step>\n</Steps>',
	"tabs-example":
		'<Tabs\n  tabs={[\n    {\n      label: "First",\n      content: <P>Content of the first panel.</P>,\n    },\n    {\n      label: "Second",\n      content: (\n        <P>Content of the second panel — any ReactNode works.</P>\n      ),\n    },\n  ]}\n/>',
} as const satisfies SnippetMap;
