// ui-studio-meta.gen.ts — auto-generated by @dennation/ui-studio, do not edit
import type { ComponentMeta } from '@dennation/ui-studio'

const meta: Record<string, ComponentMeta> = {
  "src/stories/Button.stories.tsx": {
    "props": [
      {
        "name": "size",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "sm",
            "md",
            "lg"
          ]
        }
      },
      {
        "name": "variant",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "solid",
            "outline",
            "ghost"
          ]
        }
      },
      {
        "name": "color",
        "optional": true,
        "type": {
          "kind": "literal",
          "values": [
            "primary",
            "secondary",
            "danger"
          ]
        }
      },
      {
        "name": "disabled",
        "optional": true,
        "type": {
          "kind": "boolean"
        }
      }
    ]
  }
}

export default meta
