// ui-studio-registry.gen.ts — auto-generated by @dennation/ui-studio, do not edit
import type { Registry } from '@dennation/ui-studio'
import meta from './ui-studio-meta.gen'
import _Button, { Default as _Button_Default, Sizes as _Button_Sizes, Variants as _Button_Variants, Colors as _Button_Colors, Matrix as _Button_Matrix } from './src/stories/Button.stories'
import _page from './src/docs/GettingStarted.docs'

const registry: Registry = {
  components: [
    {
      config: _Button,
      stories: { Default: _Button_Default, Sizes: _Button_Sizes, Variants: _Button_Variants, Colors: _Button_Colors, Matrix: _Button_Matrix },
      meta: meta['src/stories/Button.stories.tsx'],
    },
  ],
  pages: [
    _page,
  ],
}

export default registry
