// ui-studio-registry.gen.ts — auto-generated by @dennation/ui-studio, do not edit
import type { Registry } from '@dennation/ui-studio'
import meta from './ui-studio-meta.gen'
import _Button, { Default as _Button_Default, Sizes as _Button_Sizes, Variants as _Button_Variants, Colors as _Button_Colors, Matrix as _Button_Matrix, Disabled as _Button_Disabled } from './src/stories/Button.stories'
import _page from './src/docs/Theming.page'
import _page2 from './src/docs/GettingStarted.page'
import _page3 from './src/docs/Changelog.page'
import _page4 from './src/docs/ButtonGuide.page'

const registry: Registry = {
  components: [
    {
      config: _Button,
      stories: { Default: _Button_Default, Sizes: _Button_Sizes, Variants: _Button_Variants, Colors: _Button_Colors, Matrix: _Button_Matrix, Disabled: _Button_Disabled },
      meta: meta['src/stories/Button.stories.tsx'],
    },
  ],
  pages: [
    _page,
    _page2,
    _page3,
    _page4,
  ],
}

export default registry
