import { resolve } from 'node:path'
import { describe, expect, test } from 'vitest'
import type { PropInfo } from '../../types.js'
import { generateRegistryFile, type RegistryComponent } from '../generator.js'

const CWD = '/project'
const REGISTRY_PATH = resolve(CWD, 'src/ui-registry.gen.ts')

function comp(
	id: string,
	definingFile: string,
	name: string,
	path: string,
	props: PropInfo[] = [],
): RegistryComponent {
	return {
		id,
		definingFile,
		componentImport: { name, path },
		props,
	}
}

describe('generateRegistryFile', () => {
	test('empty input → empty object', () => {
		const result = generateRegistryFile([], REGISTRY_PATH)
		expect(result).toMatchInlineSnapshot(`
			"// ui-registry.gen.ts — auto-generated by @dennation/typebook, do not edit
			import type { UIRegistry } from '@dennation/typebook'

			export const uiRegistry = {
			} as const satisfies UIRegistry
			"
		`)
	})

	test('single component → import + entry with inline meta', () => {
		const props: PropInfo[] = [
			{ name: 'size', optional: true, type: { kind: 'literal', values: ['sm', 'md'] } },
		]
		const result = generateRegistryFile(
			[comp('button', '/project/src/pages/button.tsx', 'Button', '../components/Button', props)],
			REGISTRY_PATH,
		)

		expect(result).toContain('import { Button } from "./components/Button"')
		expect(result).toContain('"button": {')
		expect(result).toContain('componentName: "Button"')
		expect(result).toContain('component: Button')
		expect(result).toContain('"name": "size"')
	})

	test('package specifier is preserved (not made relative)', () => {
		const result = generateRegistryFile(
			[comp('button', '/project/src/pages/button.tsx', 'Button', '@heroui/button')],
			REGISTRY_PATH,
		)

		expect(result).toContain('import { Button } from "@heroui/button"')
	})

	test('name collision → second component gets aliased', () => {
		const result = generateRegistryFile(
			[
				comp('button', '/project/src/pages/a.tsx', 'Button', '../components/Button'),
				comp('button-2', '/project/src/pages/b.tsx', 'Button', '@heroui/button'),
			],
			REGISTRY_PATH,
		)

		expect(result).toContain('import { Button } from "./components/Button"')
		expect(result).toContain('import { Button as Button2 } from "@heroui/button"')
		expect(result).toContain('component: Button')
		expect(result).toContain('component: Button2')
	})

	test('inherited prop kept verbatim', () => {
		const props: PropInfo[] = [
			{ name: 'id', optional: true, type: { kind: 'string' }, inherited: true },
		]
		const result = generateRegistryFile(
			[comp('button', '/project/src/pages/button.tsx', 'Button', '../components/Button', props)],
			REGISTRY_PATH,
		)

		expect(result).toContain('"inherited": true')
	})

	test('defaultValue is emitted when present', () => {
		const props: PropInfo[] = [
			{ name: 'size', optional: true, type: { kind: 'literal', values: ['sm', 'md'] }, defaultValue: "'md'" },
		]
		const result = generateRegistryFile(
			[comp('button', '/project/src/pages/button.tsx', 'Button', '../components/Button', props)],
			REGISTRY_PATH,
		)

		expect(result).toContain(`"defaultValue": "'md'"`)
	})

	test('component with no props → empty props array on single line', () => {
		const result = generateRegistryFile(
			[comp('button', '/project/src/pages/button.tsx', 'Button', '../components/Button', [])],
			REGISTRY_PATH,
		)

		expect(result).toContain('"button": { componentName: "Button", component: Button, props: [] }')
	})
})
