import { basename, dirname, relative, resolve } from 'node:path'
import { PACKAGE_NAME } from '../constants.js'
import type { PropInfo } from '../types.js'
import type { ComponentImport } from './scanner.js'

/** One component's data ready to be emitted into the registry */
export interface RegistryComponent {
  /** Registry key (first argument of `register()`) */
  id: string
  /** Absolute path of the file containing the `register()` call (used to resolve relative component imports) */
  definingFile: string
  /** The component import descriptor (name + module specifier as written in `definingFile`) */
  componentImport: ComponentImport
  /** Extracted props metadata */
  props: PropInfo[]
}

const REGISTRY_TYPE_IMPORT = `import type { UIRegistry } from '@dennation/${PACKAGE_NAME}'`
const ENTRY_INDENT = '  '

/**
 * Generate a single TS file exporting `Record<string, ComponentMeta>`.
 * Components are imported by their original module path; meta literals sit
 * next to them in the same file.
 */
export function generateRegistryFile(
  components: RegistryComponent[],
  registryFilePath: string,
): string {
  const header = `// ${basename(registryFilePath)} — auto-generated by @dennation/${PACKAGE_NAME}, do not edit`
  const usedAliases = new Set<string>()
  const importLines: string[] = [header, REGISTRY_TYPE_IMPORT]
  const entryLines: string[] = []

  for (const { id, definingFile, componentImport, props } of components) {
    const alias = takeUniqueAlias(componentImport.name, usedAliases)
    const importPath = resolveImportPath(registryFilePath, definingFile, componentImport.path)

    importLines.push(buildImportLine(alias, componentImport.name, importPath))
    entryLines.push(buildEntry(id, alias, componentImport.name, props))
  }

  return [
    ...importLines,
    '',
    'export const uiRegistry = {',
    ...entryLines,
    '} as const satisfies UIRegistry',
    '',
  ].join('\n')
}

function buildImportLine(alias: string, exportedName: string, importPath: string): string {
  const clause = alias === exportedName ? exportedName : `${exportedName} as ${alias}`
  return `import { ${clause} } from ${JSON.stringify(importPath)}`
}

function buildEntry(id: string, alias: string, componentName: string, props: PropInfo[]): string {
  const key = JSON.stringify(id)
  const namePart = `componentName: ${JSON.stringify(componentName)}`
  const componentPart = `component: ${alias}`

  if (props.length === 0) {
    return `${ENTRY_INDENT}${key}: { ${namePart}, ${componentPart}, props: [] },`
  }

  const propsBody = JSON.stringify(props, null, 2)
    .split('\n')
    .map((line) => `${ENTRY_INDENT}${ENTRY_INDENT}${line}`)
    .join('\n')

  return [
    `${ENTRY_INDENT}${key}: {`,
    `${ENTRY_INDENT}${ENTRY_INDENT}${namePart},`,
    `${ENTRY_INDENT}${ENTRY_INDENT}${componentPart},`,
    `${ENTRY_INDENT}${ENTRY_INDENT}props: ${propsBody.trimStart()},`,
    `${ENTRY_INDENT}},`,
  ].join('\n')
}

/**
 * Build the module specifier to use in the generated registry file.
 *
 * - Package specifiers (e.g. `@heroui/button`) are kept as-is.
 * - Relative specifiers are resolved against the file that originally imported them
 *   (`definingFile`), then re-expressed relative to `registryFile`.
 * - Path separators are normalised to POSIX so the file is portable across OSes.
 */
function resolveImportPath(registryFile: string, definingFile: string, importSpecifier: string): string {
  if (!isRelativeSpecifier(importSpecifier)) {
    return importSpecifier
  }

  const absolute = resolve(dirname(definingFile), importSpecifier)
  const rel = relative(dirname(registryFile), absolute)
    .replace(/\.tsx?$/, '')
    .replace(/\\/g, '/')

  return rel.startsWith('.') ? rel : `./${rel}`
}

function isRelativeSpecifier(spec: string): boolean {
  return spec.startsWith('.') || spec.startsWith('/')
}

/** Reserve a unique alias for `base`, mutating `used` to mark it taken. */
function takeUniqueAlias(base: string, used: Set<string>): string {
  let candidate = base
  let i = 2
  while (used.has(candidate)) {
    candidate = `${base}${i}`
    i++
  }
  used.add(candidate)
  return candidate
}
