import { basename } from "node:path";
import { PACKAGE_NAME } from "../constants.js";

/** One extracted snippet ready to be emitted into the generated map. */
export interface SnippetEntry {
	/** The `name` prop — becomes the map key */
	name: string;
	/** Exact extracted source text */
	code: string;
}

const SNIPPET_TYPE_IMPORT = `import type { SnippetMap } from '@dennation/${PACKAGE_NAME}'`;

/**
 * Generate a single TS file exporting `Record<string, string>` — each
 * `<Snippet name>`'s extracted source keyed by its name. Mirrors
 * {@link generateRegistryFile}: a physical file on disk so `tsc` sees it, PR
 * diffs show what changed, and the runtime imports it (no runtime fetch).
 * Entries are sorted by name for stable output.
 */
export function generateSnippetsFile(
	entries: SnippetEntry[],
	snippetsFilePath: string,
): string {
	const header = `// ${basename(snippetsFilePath)} — auto-generated by @dennation/${PACKAGE_NAME}, do not edit`;

	const sorted = [...entries].sort((a, b) =>
		a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
	);
	const entryLines = sorted.map(
		({ name, code }) => `  ${JSON.stringify(name)}: ${JSON.stringify(code)},`,
	);

	return [
		header,
		SNIPPET_TYPE_IMPORT,
		"",
		"export const snippets = {",
		...entryLines,
		"} as const satisfies SnippetMap",
		"",
	].join("\n");
}
