import { resolve } from 'node:path'
import { describe, test, expect } from 'vitest'
import { generateMetaFile, generateRegistryFile } from '../generator.js'
import type { PropInfo } from '../../types.js'
import type { StoryAnalysis, PageAnalysis } from '../scanner.js'
import type { PageFileInfo } from '../generator.js'

const CWD = '/project'

function makeFile(
	filePath: string,
	analysis: StoryAnalysis,
	props: PropInfo[] = [],
) {
	return { filePath, analysis, props }
}

function makeAnalysis(overrides: Partial<StoryAnalysis> = {}): StoryAnalysis {
	return {
		defaultExport: true,
		namedExports: [],
		componentImport: null,
		...overrides,
	}
}

function makePageFile(
	filePath: string,
	analysis: PageAnalysis = { defaultExport: true },
): PageFileInfo {
	return { filePath, analysis }
}

// --- generateMetaFile ---

describe('generateMetaFile', () => {
	test('empty files → valid empty meta', () => {
		const result = generateMetaFile([], CWD)
		expect(result).toMatchInlineSnapshot(`
			"// ui-studio-meta.gen.ts — auto-generated by @dennation/ui-studio, do not edit
			import type { ComponentMeta } from '@dennation/ui-studio'

			const meta: Record<string, ComponentMeta> = {}

			export default meta
			"
		`)
	})

	test('single file with props → keyed by relative path', () => {
		const props: PropInfo[] = [
			{ name: 'size', optional: true, type: { kind: 'literal', values: ['sm', 'md'] } },
			{ name: 'disabled', optional: false, type: { kind: 'boolean' } },
		]
		const result = generateMetaFile(
			[makeFile('/project/src/Button.stories.tsx', makeAnalysis(), props)],
			CWD,
		)
		// Verify the key is the relative path
		expect(result).toContain('"src/Button.stories.tsx"')
		// Verify each prop is correctly associated with its type
		const parsed = extractMeta(result)
		const entry = parsed['src/Button.stories.tsx']
		expect(entry.props).toEqual([
			{ name: 'size', optional: true, type: { kind: 'literal', values: ['sm', 'md'] } },
			{ name: 'disabled', optional: false, type: { kind: 'boolean' } },
		])
	})

	test('multiple files → all keyed', () => {
		const result = generateMetaFile([
			makeFile('/project/src/A.stories.tsx', makeAnalysis(), []),
			makeFile('/project/src/B.stories.tsx', makeAnalysis(), []),
		], CWD)
		const parsed = extractMeta(result)
		expect(Object.keys(parsed)).toEqual(['src/A.stories.tsx', 'src/B.stories.tsx'])
	})

	test('file with no props → empty props array', () => {
		const result = generateMetaFile(
			[makeFile('/project/src/Empty.stories.tsx', makeAnalysis(), [])],
			CWD,
		)
		const parsed = extractMeta(result)
		expect(parsed['src/Empty.stories.tsx'].props).toEqual([])
	})

	test('all prop types serialized correctly', () => {
		const props: PropInfo[] = [
			{ name: 'a', optional: false, type: { kind: 'string' } },
			{ name: 'b', optional: false, type: { kind: 'number' } },
			{ name: 'c', optional: false, type: { kind: 'boolean' } },
			{ name: 'd', optional: false, type: { kind: 'node' } },
			{ name: 'e', optional: false, type: { kind: 'function' } },
			{ name: 'f', optional: false, type: { kind: 'unknown', raw: 'SomeType' } },
		]
		const result = generateMetaFile(
			[makeFile('/project/src/All.stories.tsx', makeAnalysis(), props)],
			CWD,
		)
		const parsed = extractMeta(result)
		expect(parsed['src/All.stories.tsx'].props).toEqual(props)
	})
})

/** Extract the meta object from the generated source */
function extractMeta(source: string): Record<string, { props: PropInfo[] }> {
	const match = source.match(/= (\{[\s\S]*\})/)
	if (!match) throw new Error('Could not find meta object in source')
	return JSON.parse(match[1])
}

// --- generateRegistryFile ---

const REGISTRY_PATH = resolve(CWD, 'ui-studio-registry.gen.ts')
const META_PATH = resolve(CWD, 'ui-studio-meta.gen.ts')

describe('generateRegistryFile', () => {
	test('empty files → valid empty registry', () => {
		const result = generateRegistryFile([], [], REGISTRY_PATH, META_PATH, CWD)
		expect(result).toMatchInlineSnapshot(`
			"// ui-studio-registry.gen.ts — auto-generated by @dennation/ui-studio, do not edit
			import type { Registry } from '@dennation/ui-studio'
			import meta from './ui-studio-meta.gen'

			const registry: Registry = {
			  components: [
			  ],
			  pages: [
			  ],
			}

			export default registry
			"
		`)
	})

	test('single file with default + named exports', () => {
		const file = makeFile(
			'/project/src/stories/Button.stories.tsx',
			makeAnalysis({
				defaultExport: true,
				namedExports: ['Default', 'Sizes'],
				componentImport: { name: 'Button', path: '@heroui/button' },
			}),
		)
		const result = generateRegistryFile([file], [], REGISTRY_PATH, META_PATH, CWD)
		expect(result).toContain("import _Button, { Default as _Button_Default, Sizes as _Button_Sizes } from './src/stories/Button.stories'")
		expect(result).toContain('config: _Button,')
		expect(result).toContain('stories: { Default: _Button_Default, Sizes: _Button_Sizes },')
		expect(result).toContain("meta: meta['src/stories/Button.stories.tsx'],")
	})

	test('file with only named exports (no default) → skipped from registry', () => {
		const file = makeFile(
			'/project/src/stories/Input.stories.tsx',
			makeAnalysis({
				defaultExport: false,
				namedExports: ['Default', 'Sizes'],
				componentImport: { name: 'Input', path: './Input' },
			}),
		)
		const result = generateRegistryFile([file], [], REGISTRY_PATH, META_PATH, CWD)

		// No import line for file without default export
		expect(result).not.toContain('_Input')
		// No registry entry — config (DefineResult) is required
		expect(result).not.toContain('stories:')
	})

	test('file with only default export (no named)', () => {
		const file = makeFile(
			'/project/src/stories/Switch.stories.tsx',
			makeAnalysis({
				defaultExport: true,
				namedExports: [],
				componentImport: { name: 'Switch', path: './Switch' },
			}),
		)
		const result = generateRegistryFile([file], [], REGISTRY_PATH, META_PATH, CWD)
		expect(result).toContain("import _Switch from './src/stories/Switch.stories'")
		expect(result).toContain('config: _Switch,')
		expect(result).toContain('stories: {  },')
	})

	test('name collision → unique prefixes', () => {
		const files = [
			makeFile(
				'/project/src/a/Button.stories.tsx',
				makeAnalysis({
					namedExports: ['Default'],
					componentImport: { name: 'Button', path: './a/Button' },
				}),
			),
			makeFile(
				'/project/src/b/Button.stories.tsx',
				makeAnalysis({
					namedExports: ['Default'],
					componentImport: { name: 'Button', path: './b/Button' },
				}),
			),
		]
		const result = generateRegistryFile(files, [], REGISTRY_PATH, META_PATH, CWD)

		// Verify complete import lines for each file
		expect(result).toContain("import _Button, { Default as _Button_Default } from './src/a/Button.stories'")
		expect(result).toContain("import _Button2, { Default as _Button2_Default } from './src/b/Button.stories'")

		// Verify config references match the imported names
		expect(result).toContain('config: _Button,')
		expect(result).toContain('config: _Button2,')

		// Verify stories reference correct aliases
		expect(result).toContain('stories: { Default: _Button_Default }')
		expect(result).toContain('stories: { Default: _Button2_Default }')

		// Meta keys are distinct
		expect(result).toContain("meta['src/a/Button.stories.tsx']")
		expect(result).toContain("meta['src/b/Button.stories.tsx']")
	})

	test('three components with same name → _X, _X2, _X3', () => {
		const files = [
			makeFile('/project/src/a/Card.stories.tsx', makeAnalysis({
				namedExports: ['Default'],
				componentImport: { name: 'Card', path: './a/Card' },
			})),
			makeFile('/project/src/b/Card.stories.tsx', makeAnalysis({
				namedExports: ['Default'],
				componentImport: { name: 'Card', path: './b/Card' },
			})),
			makeFile('/project/src/c/Card.stories.tsx', makeAnalysis({
				namedExports: ['Default'],
				componentImport: { name: 'Card', path: './c/Card' },
			})),
		]
		const result = generateRegistryFile(files, [], REGISTRY_PATH, META_PATH, CWD)

		expect(result).toContain('config: _Card,')
		expect(result).toContain('config: _Card2,')
		expect(result).toContain('config: _Card3,')
	})

	test('no componentImport → fallback to Component{index}', () => {
		const files = [
			makeFile('/project/src/A.stories.tsx', makeAnalysis({
				namedExports: ['Foo'],
				componentImport: null,
			})),
			makeFile('/project/src/B.stories.tsx', makeAnalysis({
				namedExports: ['Bar'],
				componentImport: null,
			})),
		]
		const result = generateRegistryFile(files, [], REGISTRY_PATH, META_PATH, CWD)

		// Each file gets a unique Component{index} prefix
		expect(result).toContain('config: _Component0,')
		expect(result).toContain('Foo as _Component0_Foo')
		expect(result).toContain('config: _Component1,')
		expect(result).toContain('Bar as _Component1_Bar')
	})

	test('mixed: file without default export skipped, file with default kept', () => {
		const files = [
			makeFile('/project/src/A.stories.tsx', makeAnalysis({
				defaultExport: false,
				namedExports: ['Foo'],
				componentImport: null,
			})),
			makeFile('/project/src/B.stories.tsx', makeAnalysis({
				defaultExport: true,
				namedExports: ['Bar'],
				componentImport: { name: 'B', path: './B' },
			})),
		]
		const result = generateRegistryFile(files, [], REGISTRY_PATH, META_PATH, CWD)

		// Only B should appear in the registry
		expect(result).not.toContain('_Component')
		expect(result).toContain('config: _B,')
		expect(result).toContain('Bar as _B_Bar')
	})

	test('relative import paths computed from registry location', () => {
		const registryPath = resolve(CWD, 'generated/registry.gen.ts')
		const metaPath = resolve(CWD, 'generated/meta.gen.ts')
		const file = makeFile(
			'/project/src/stories/Button.stories.tsx',
			makeAnalysis({
				namedExports: ['Default'],
				componentImport: { name: 'Button', path: '@heroui/button' },
			}),
		)
		const result = generateRegistryFile([file], [], registryPath, metaPath, CWD)

		// Import should go up from generated/ to src/stories/
		expect(result).toContain("from '../src/stories/Button.stories'")
		expect(result).toContain("import meta from './meta.gen'")
	})

	test('.tsx extension stripped from import paths but preserved in meta keys', () => {
		const file = makeFile(
			'/project/src/Button.stories.tsx',
			makeAnalysis({
				namedExports: ['Default'],
				componentImport: { name: 'Button', path: './Button' },
			}),
		)
		const result = generateRegistryFile([file], [], REGISTRY_PATH, META_PATH, CWD)

		// Import path should not contain .tsx
		expect(result).toContain("from './src/Button.stories'")
		expect(result).not.toMatch(/from '.*\.tsx'/)
		// But meta key legitimately contains .tsx (it's a file path, not an import)
		expect(result).toContain("meta['src/Button.stories.tsx']")
	})

	test('multiple files → entries in input order', () => {
		const files = [
			makeFile('/project/src/A.stories.tsx', makeAnalysis({
				namedExports: ['X'],
				componentImport: { name: 'A', path: './A' },
			})),
			makeFile('/project/src/B.stories.tsx', makeAnalysis({
				namedExports: ['Y'],
				componentImport: { name: 'B', path: './B' },
			})),
			makeFile('/project/src/C.stories.tsx', makeAnalysis({
				namedExports: ['Z'],
				componentImport: { name: 'C', path: './C' },
			})),
		]
		const result = generateRegistryFile(files, [], REGISTRY_PATH, META_PATH, CWD)

		const configA = result.indexOf('config: _A,')
		const configB = result.indexOf('config: _B,')
		const configC = result.indexOf('config: _C,')
		expect(configA).toBeGreaterThan(-1)
		expect(configB).toBeGreaterThan(-1)
		expect(configC).toBeGreaterThan(-1)
		expect(configA).toBeLessThan(configB)
		expect(configB).toBeLessThan(configC)
	})
})

// --- generateRegistryFile with pages ---

describe('generateRegistryFile with pages', () => {
	test('page files with default export → pages array populated', () => {
		const pageFile = makePageFile('/project/src/docs/GettingStarted.docs.tsx')
		const result = generateRegistryFile([], [pageFile], REGISTRY_PATH, META_PATH, CWD)

		expect(result).toContain("import _page from './src/docs/GettingStarted.docs'")
		expect(result).toContain('_page,')
	})

	test('page file without default export → skipped', () => {
		const pageFile = makePageFile('/project/src/docs/Empty.docs.tsx', { defaultExport: false })
		const result = generateRegistryFile([], [pageFile], REGISTRY_PATH, META_PATH, CWD)

		expect(result).not.toContain('_page')
		expect(result).toContain('pages: [\n  ],')
	})

	test('multiple page files → unique prefixes', () => {
		const pageFiles = [
			makePageFile('/project/src/docs/Guide.docs.tsx'),
			makePageFile('/project/src/docs/Changelog.docs.tsx'),
		]
		const result = generateRegistryFile([], pageFiles, REGISTRY_PATH, META_PATH, CWD)

		expect(result).toContain("import _page from './src/docs/Guide.docs'")
		expect(result).toContain("import _page2 from './src/docs/Changelog.docs'")
		expect(result).toContain('_page,')
		expect(result).toContain('_page2,')
	})

	test('empty page files → pages: []', () => {
		const result = generateRegistryFile([], [], REGISTRY_PATH, META_PATH, CWD)
		expect(result).toContain('pages: [\n  ],')
	})

	test('components and pages together', () => {
		const storyFile = makeFile(
			'/project/src/stories/Button.stories.tsx',
			makeAnalysis({
				defaultExport: true,
				namedExports: ['Default'],
				componentImport: { name: 'Button', path: '@heroui/button' },
			}),
		)
		const pageFile = makePageFile('/project/src/docs/Guide.docs.tsx')
		const result = generateRegistryFile([storyFile], [pageFile], REGISTRY_PATH, META_PATH, CWD)

		expect(result).toContain('config: _Button,')
		expect(result).toContain('_page,')
	})
})

