import { relative, dirname } from 'node:path'
import type { PropInfo } from '../types.js'
import type { analyzeStoryFile } from './scanner.js'
import { PACKAGE_NAME, DEFAULT_GEN_FILE } from '../constants.js'

interface StoryFileInfo {
  filePath: string
  analysis: ReturnType<typeof analyzeStoryFile>
  props: PropInfo[]
}

/**
 * Generate the content of studio.gen.ts from analyzed story files.
 */
export function generateStudioGenFile(
  files: StoryFileInfo[],
  genFilePath: string,
): string {
  const importLines: string[] = [
    `// ${DEFAULT_GEN_FILE.replace('./', '')} — auto-generated by @dennation/${PACKAGE_NAME}, do not edit`,
    `import { resolve } from '@dennation/${PACKAGE_NAME}'`,
    `import type { PropInfo } from '@dennation/${PACKAGE_NAME}'`,
  ]

  const bodyLines: string[] = []
  const componentVars: string[] = []
  const usedPrefixes = new Set<string>()

  for (let i = 0; i < files.length; i++) {
    const { filePath, analysis, props } = files[i]
    const baseName = analysis.componentImport?.name ?? `Component${i}`
    const prefix = getUniquePrefix(baseName, usedPrefixes)
    usedPrefixes.add(prefix)
    const importPath = buildRelativeImport(genFilePath, filePath)

    // Build import statement
    const imports: string[] = []
    if (analysis.defaultExport) {
      imports.push(prefix)
    }
    for (const name of analysis.namedExports) {
      imports.push(`${name} as ${prefix}_${name}`)
    }

    if (imports.length > 0) {
      importLines.push(`import ${formatImports(imports, analysis.defaultExport, prefix)} from '${importPath}'`)
    }

    // Generate props constant
    const propsVar = `${prefix}Props`
    bodyLines.push(`const ${propsVar}: PropInfo[] = ${JSON.stringify(props, null, 2)}`)

    // Build stories array
    const storiesEntries = analysis.namedExports.map(
      (name) => `{ name: '${name}', story: ${prefix}_${name} }`,
    )

    // resolve call
    bodyLines.push('')
    bodyLines.push(`const ${prefix}Resolved = resolve(${prefix}, {`)
    bodyLines.push(`  props: ${propsVar},`)
    bodyLines.push(`  stories: [${storiesEntries.join(', ')}],`)
    bodyLines.push('})')
    bodyLines.push('')

    componentVars.push(`${prefix}Resolved`)
  }

  // Default export — array of resolved components
  bodyLines.push(`export default [${componentVars.join(', ')}]`)
  bodyLines.push('')

  return [...importLines, '', ...bodyLines].join('\n')
}

function formatImports(
  imports: string[],
  hasDefault: boolean,
  defaultName: string,
): string {
  if (hasDefault) {
    const named = imports.filter((i) => i !== defaultName)
    if (named.length > 0) {
      return `${defaultName}, { ${named.join(', ')} }`
    }
    return defaultName
  }
  return `{ ${imports.join(', ')} }`
}

function buildRelativeImport(from: string, to: string): string {
  const fromDir = dirname(from)
  let rel = relative(fromDir, to)
  // Remove .tsx extension for import
  rel = rel.replace(/\.tsx?$/, '')
  // Ensure relative path
  if (!rel.startsWith('.')) {
    rel = './' + rel
  }
  return rel
}

function getUniquePrefix(name: string, used: Set<string>): string {
  // Add underscore prefix (Button -> _Button)
  const base = `_${name}`
  if (!used.has(base)) return base
  // Add suffix if collision
  let i = 2
  while (used.has(`${base}${i}`)) i++
  return `${base}${i}`
}
