import { relative, dirname, basename } from 'node:path'
import type { PropInfo } from '../types.js'
import type { StoryAnalysis, PageAnalysis } from './scanner.js'
import { PACKAGE_NAME, DEFAULT_REGISTRY_FILE, DEFAULT_META_FILE } from '../constants.js'

interface StoryFileInfo {
  filePath: string
  analysis: StoryAnalysis
  props: PropInfo[]
}

export interface PageFileInfo {
  filePath: string
  analysis: PageAnalysis
}

/**
 * Generate the content of the meta gen file — extracted component metadata.
 * Keyed by story file path (relative to project root).
 */
export function generateMetaFile(
  files: StoryFileInfo[],
  cwd: string,
): string {
  const metaEntries = Object.fromEntries(
    files.map(({ filePath, props }) => [
      relative(cwd, filePath),
      { props: props.map(cleanPropInfo) },
    ]),
  )

  const lines: string[] = [
    `// ${basename(DEFAULT_META_FILE)} — auto-generated by @dennation/${PACKAGE_NAME}, do not edit`,
    `import type { ComponentMeta } from '@dennation/${PACKAGE_NAME}'`,
    '',
    `const meta: Record<string, ComponentMeta> = ${JSON.stringify(metaEntries, null, 2)}`,
    '',
    'export default meta',
    '',
  ]

  return lines.join('\n')
}

/**
 * Generate the content of the registry gen file — imports stories, configs, pages, and meta.
 */
export function generateRegistryFile(
  files: StoryFileInfo[],
  pageFiles: PageFileInfo[],
  registryFilePath: string,
  metaFilePath: string,
  cwd: string,
): string {
  const importLines: string[] = [
    `// ${basename(DEFAULT_REGISTRY_FILE)} — auto-generated by @dennation/${PACKAGE_NAME}, do not edit`,
    `import type { Registry } from '@dennation/${PACKAGE_NAME}'`,
  ]

  const metaImportPath = buildRelativeImport(registryFilePath, metaFilePath)
  importLines.push(`import meta from '${metaImportPath}'`)

  const entryLines: string[] = []
  const usedPrefixes = new Set<string>()

  for (let i = 0; i < files.length; i++) {
    const { filePath, analysis } = files[i]

    // Skip files without a default export — config (DefineResult) is required
    if (!analysis.defaultExport) continue

    const baseName = analysis.componentImport?.name ?? `Component${i}`
    const prefix = getUniquePrefix(baseName, usedPrefixes)
    usedPrefixes.add(prefix)
    const importPath = buildRelativeImport(registryFilePath, filePath)
    const fileKey = relative(cwd, filePath)

    // Build import statement
    const namedImports = analysis.namedExports.map((name) => `${name} as ${prefix}_${name}`)
    const importClause = namedImports.length > 0
      ? `${prefix}, { ${namedImports.join(', ')} }`
      : prefix
    importLines.push(`import ${importClause} from '${importPath}'`)

    // Build stories record
    const storiesEntries = analysis.namedExports.map(
      (name) => `${name}: ${prefix}_${name}`,
    )

    // Build registry entry
    entryLines.push(`  {`)
    entryLines.push(`    config: ${prefix},`)
    entryLines.push(`    stories: { ${storiesEntries.join(', ')} },`)
    entryLines.push(`    meta: meta['${fileKey}'],`)
    entryLines.push(`  },`)
  }

  // Page imports and entries
  const pageEntryLines: string[] = []

  for (const pageFile of pageFiles) {
    const { filePath, analysis } = pageFile
    if (!analysis.defaultExport) continue
    const prefix = getUniquePrefix('page', usedPrefixes)
    usedPrefixes.add(prefix)
    const importPath = buildRelativeImport(registryFilePath, filePath)

    importLines.push(`import ${prefix} from '${importPath}'`)
    pageEntryLines.push(`    ${prefix},`)
  }

  const bodyLines: string[] = [
    '',
    `const registry: Registry = {`,
    `  components: [`,
    ...entryLines.map((line) => `  ${line}`),
    `  ],`,
    `  pages: [`,
    ...pageEntryLines,
    `  ],`,
    `}`,
    '',
    'export default registry',
    '',
  ]

  return [...importLines, ...bodyLines].join('\n')
}

/** Strip `inherited` when falsy to keep the meta file clean — only emit `"inherited": true` */
function cleanPropInfo(prop: PropInfo): object {
  const { inherited, ...rest } = prop
  return inherited ? { ...rest, inherited } : rest
}

function buildRelativeImport(from: string, to: string): string {
  const fromDir = dirname(from)
  let rel = relative(fromDir, to)
  rel = rel.replace(/\.tsx?$/, '')
  // Ensure relative path
  if (!rel.startsWith('.')) {
    rel = './' + rel
  }
  return rel
}

function getUniquePrefix(name: string, used: Set<string>): string {
  const base = `_${name}`
  if (!used.has(base)) return base
  let i = 2
  while (used.has(`${base}${i}`)) i++
  return `${base}${i}`
}
