import { relative, dirname } from 'node:path'
import type { PropInfo } from '../types.js'
import type { analyzeStoryFile } from './scanner.js'
import { PACKAGE_NAME, DEFAULT_GEN_FILE } from '../constants.js'

interface StoryFileInfo {
  filePath: string
  analysis: ReturnType<typeof analyzeStoryFile>
  props: PropInfo[]
  /** Per-part props for compound components */
  partProps?: Record<string, PropInfo[]>
}

/**
 * Generate the content of studio.gen.ts from analyzed story files.
 */
export function generateStudioGenFile(
  files: StoryFileInfo[],
  genFilePath: string,
): string {
  // Check if any file is compound to decide whether to import resolveCompound
  const hasCompound = files.some((f) => f.analysis.compound)

  const resolveImports = ['resolve']
  if (hasCompound) resolveImports.push('resolveCompound')

  const lines: string[] = [
    `// ${DEFAULT_GEN_FILE.replace('./', '')} — auto-generated by @dennation/${PACKAGE_NAME}, do not edit`,
    `import { ${resolveImports.join(', ')} } from '@dennation/${PACKAGE_NAME}'`,
    `import type { PropInfo } from '@dennation/${PACKAGE_NAME}'`,
    '',
  ]

  const componentVars: string[] = []
  const usedPrefixes = new Set<string>()

  for (let i = 0; i < files.length; i++) {
    const { filePath, analysis, props, partProps } = files[i]
    const baseName = analysis.componentImport?.name ?? `Component${i}`
    const prefix = getUniquePrefix(baseName, usedPrefixes)
    usedPrefixes.add(prefix)
    const importPath = buildRelativeImport(genFilePath, filePath)

    // Build import statement
    const imports: string[] = []
    if (analysis.defaultExport) {
      imports.push(prefix)
    }
    for (const name of analysis.namedExports) {
      imports.push(`${name} as ${prefix}_${name}`)
    }

    if (imports.length > 0) {
      lines.push(`import ${formatImports(imports, analysis.defaultExport, prefix)} from '${importPath}'`)
    }

    // Build stories array (shared between both paths)
    const storiesEntries = analysis.namedExports.map(
      (name) => `{ name: '${name}', story: ${prefix}_${name} }`,
    )

    if (analysis.compound && partProps) {
      // Compound component: generate per-part props and resolveCompound() call
      const partPropsVar = `${prefix}PartProps`
      lines.push('')
      lines.push(`const ${partPropsVar}: Record<string, PropInfo[]> = ${JSON.stringify(partProps, null, 2)}`)

      lines.push('')
      lines.push(`const ${prefix}Resolved = resolveCompound(${prefix}, {`)
      lines.push(`  partProps: ${partPropsVar},`)
      lines.push(`  stories: [${storiesEntries.join(', ')}],`)
      lines.push('})')
    } else {
      // Regular component: existing behavior
      const propsVar = `${prefix}Props`
      lines.push('')
      lines.push(`const ${propsVar}: PropInfo[] = ${JSON.stringify(props, null, 2)}`)

      lines.push('')
      lines.push(`const ${prefix}Resolved = resolve(${prefix}, {`)
      lines.push(`  props: ${propsVar},`)
      lines.push(`  stories: [${storiesEntries.join(', ')}],`)
      lines.push('})')
    }

    componentVars.push(`${prefix}Resolved`)
  }

  // Default export — array of resolved components
  lines.push('')
  lines.push(`export default [${componentVars.join(', ')}]`)
  lines.push('')

  return lines.join('\n')
}

function formatImports(
  imports: string[],
  hasDefault: boolean,
  defaultName: string,
): string {
  if (hasDefault) {
    const named = imports.filter((i) => i !== defaultName)
    if (named.length > 0) {
      return `${defaultName}, { ${named.join(', ')} }`
    }
    return defaultName
  }
  return `{ ${imports.join(', ')} }`
}

function buildRelativeImport(from: string, to: string): string {
  const fromDir = dirname(from)
  let rel = relative(fromDir, to)
  // Remove .tsx extension for import
  rel = rel.replace(/\.tsx?$/, '')
  // Ensure relative path
  if (!rel.startsWith('.')) {
    rel = './' + rel
  }
  return rel
}

function getUniquePrefix(name: string, used: Set<string>): string {
  // Add underscore prefix (Button -> _Button)
  const base = `_${name}`
  if (!used.has(base)) return base
  // Add suffix if collision
  let i = 2
  while (used.has(`${base}${i}`)) i++
  return `${base}${i}`
}
